apiVersion: v1
kind: Service
metadata:
  name: agtwo-coll-550473fa392d439e92dfcf4f24e7f650-srv
spec:
  selector:
    app: agtwo-coll-550473fa392d439e92dfcf4f24e7f650
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9030
  type: ClusterIP